### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by liamxg** [veg/hivtrace#109]
Dear Prof. @spond,

Please see below:

```

hivtrace -i TEST.FASTA -a resolve -r HXB2_prrt -t .015 -m 500 -g .05 -c
Traceback (most recent call last):
  File "/Users/liam/opt/miniconda3/bin/bealign", line 16, in <module>
  from BioExt.scorematrices import (
    File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/BioExt/scorematrices/__init__.py", line 4, in <module>
      from BioExt.scorematrices._scorematrix import *
      File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/BioExt/scorematrices/_scorematrix.py", line 12, in <module>
      from BioExt.optimize import minimize_bfgs
    File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/BioExt/optimize/__init__.py", line 193, in <module>
      tol=1e-5, norm=numpy.Inf, eps=_epsilon, maxiter=None,
    File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
      AttributeError: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.
      Traceback (most recent call last):
        File "/Users/liam/opt/miniconda3/bin/hivtrace", line 8, in <module>
        sys.exit(main())
      File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/hivtrace/hivtrace.py", line 793, in main
      results = hivtrace(
        File "/Users/liam/opt/miniconda3/lib/python3.9/site-packages/hivtrace/hivtrace.py", line 438, in hivtrace
        subprocess.check_call(bealign_process, stdout=DEVNULL)
        File "/Users/liam/opt/miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['/Users/liam/opt/miniconda3/bin/bealign', '-q', '-r', 'HXB2_prrt', '-m', 'HIV_BETWEEN_F', '-R', 'TEST.FASTA', '/var/folders/q4/gvrdsnj94vl527nfhj25rxh40000gn/T/hivtrace-pa1fw79s/TEST.FASTA_output.bam']' returned non-zero exit status 1.
```

**Comment by stevenweaver** [comment]
Dear @liamxg, 

Can you please update `BioExt`? `pip install -U bioext`. 

Best,
Steven
