### ISSUE TITLE
pysam version mismatch

### ISSUE THREAD

**Issue by stevenweaver** [veg/hivtrace#14]
When I tried to install HIV-TRACE via homebrew, the entire installation went well, but when I tried to run the program, I was greeted with the following error message : 

```
Traceback (most recent call last):
  File "/usr/local/Cellar/hivtrace/0.2.2/libexec/bin/hivtrace", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3015, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2999, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3028, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pysam==0.8.4' distribution was not found and is required by biopython-extensions
```

How can I resolve this issue?

**Comment by stevenweaver** [comment]
Hello @stevenweaver,
I believe you may have accidentally upgraded pysam at some point after installation. 
Can you please try the following?

```
pip3 install pysam==0.8.4
```

Alternatively, you can create a virtual environment to ensure that hivtrace does not conflict with another software package you are using via `virtualenv`.
