### ISSUE TITLE
is there any step by step use of hivtrace?

### ISSUE THREAD

**Issue by BEAST-Community** [veg/hivtrace#78]
i really need materials about how to use hivtrace, anyone can help me? thanks.

**Comment by stevenweaver** [comment]
Hi @BEAST-Community, 

Do you mean something more than what is already in the README.md? 

Best,
Steven

**Comment by BEAST-Community** [comment]
@stevenweaver yes, step-by-step with real data.

**Comment by BEAST-Community** [comment]
a have a project need this analysis, could you please help me out, thanks.

**Comment by spond** [comment]
Dear @BEAST-Community,

Take a look at https://github.com/veg/kpnet-global for a detailed HIV-TRACE analysis that is worked through with real data and published in a paper.

Best,
Sergei

**Comment by BEAST-Community** [comment]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/hivtrace", line 11, in <module>
    load_entry_point('hivtrace==0.6.2', 'console_scripts', 'hivtrace')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hivtrace/hivtrace.py", line 807, in main
    prior=PRIOR
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hivtrace/hivtrace.py", line 704, in hivtrace
    annotate_lanl(LANL_OUTPUT_CLUSTER_JSON, LANL_FASTA)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hivtrace/hivtrace.py", line 252, in annotate_lanl
    node_ids = set([n["id"] for n in nodes])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hivtrace/hivtrace.py", line 252, in <listcomp>
    node_ids = set([n["id"] for n in nodes])
TypeError: string indices must be integers

**Comment by BEAST-Community** [comment]
@spond thanks for your help, i still have problem on this programm.
