### ISSUE TITLE
reference issues

### ISSUE THREAD

**Issue by braukmann** [veg/hivtrace#99]
I install hivtrace using pip as recommended and everything seems to install just fine. However whenever I go to run hivtrace it runs into this error: (installed in conda environment with python 3.9.18).

Traceback (most recent call last):
  File "/home/U1/miniconda3/envs/hivtrace/bin/bealign", line 143, in <module>
    add_reference(parser, '-r', '--reference')
  File "/home/U1/miniconda3/envs/hivtrace/lib/python3.9/site-packages/BioExt/args/__init__.py", line 33, in add_reference
    'HXB2_env': hxb2.env,
AttributeError: 'hxb2' object has no attribute 'env'
Traceback (most recent call last):
  File "/home/U1/miniconda3/envs/hivtrace/bin/hivtrace", line 8, in <module>
    sys.exit(main())
  File "/home/U1/miniconda3/envs/hivtrace/lib/python3.9/site-packages/hivtrace/hivtrace.py", line 793, in main
    results = hivtrace(
  File "/home/U1/miniconda3/envs/hivtrace/lib/python3.9/site-packages/hivtrace/hivtrace.py", line 438, in hivtrace
    subprocess.check_call(bealign_process, stdout=DEVNULL)
  File "/home/U1/miniconda3/envs/hivtrace/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/U1/miniconda3/envs/hivtrace/bin/bealign', '-q', '-r', 'HXB2_pol', '-m', 'HIV_BETWEEN_F', '-R', 'test.fa', '/tmp/hivtrace-o4lya0pf/test.fa_output.bam']' returned non-zero exit status 1.

Thank you for the help!

**Comment by braukmann** [comment]
I fixed my issue by reverting to bioext==0.21.0 and installed a local version of tn93 (as the pip installed version could not be found by my system).

**Comment by stevenweaver** [comment]
Dear @braukmann, 

Sorry for delayed response, I had been quite ill last week. Thanks for following up, and yes, later versions of bioext have been updated to support Python 3.10+. I'll try updating the documentation to reflect this.

Best,
Steven

**Comment by braukmann** [comment]
Dear Steven,

I hope you feel better soon. Thank you for update on bioext and thank you for maintaining hivtrace for so long!

Cheers,

Tom

**Comment by stevenweaver** [comment]
The issue has been fully resolved in 0.21.5
